HELMA20250404.AppMVCCore/Controllers/AulasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HELMA20250404.AppMVCCore.Models;
using Microsoft.AspNetCore.Authorization;

namespace HELMA20250404.AppMVCCore.Controllers
{
   
    public class AulasController : Controller
    {
        private readonly SistemaCalificacionesContext _context;

        public AulasController(SistemaCalificacionesContext context)
        {
            _context = context;
        }

        // GET: Aulas
        public async Task<IActionResult> Index(Aula aula, int topRegistro = 10)
        {
            var query = _context.Aulas.AsQueryable();
            if (!string.IsNullOrWhiteSpace(aula.Nombre))
                query = query.Where(s => s.Nombre.Contains(aula.Nombre));

            if (topRegistro > 0)
                query = query.Take(topRegistro);
            return View(await query.ToListAsync());
        }

        // GET: Aulas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = await _context.Aulas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aula == null)
            {
                return NotFound();
            }

            return View(aula);
        }

        // GET: Aulas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aulas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre")] Aula aula)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aula);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aula);
        }

        // GET: Aulas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = await _context.Aulas.FindAsync(id);
            if (aula == null)
            {
                return NotFound();
            }
            return View(aula);
        }

        // POST: Aulas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre")] Aula aula)
        {
            if (id != aula.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aula);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AulaExists(aula.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aula);
        }

        // GET: Aulas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = await _context.Aulas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aula == null)
            {
                return NotFound();
            }

            return View(aula);
        }

        // POST: Aulas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aula = await _context.Aulas.FindAsync(id);
            if (aula != null)
            {
                _context.Aulas.Remove(aula);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AulaExists(int id)
        {
            return _context.Aulas.Any(e => e.Id == id);
        }
    }
}

HELMA20250404.AppMVCCore/Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HELMA20250404.AppMVCCore.Models;
using Microsoft.AspNetCore.Authorization;

namespace HELMA20250404.AppMVCCore.Controllers
{
    public class NotasController : Controller
    {
        private readonly SistemaCalificacionesContext _context;
        private object usuario;

        public NotasController(SistemaCalificacionesContext context)
        {
            _context = context;
        }

        // GET: Notas
        public async Task<IActionResult> Index(Nota nota, int topRegistro = 10)
        {
            var query = _context.Notas
                .Include(n => n.Matricula)
                    .ThenInclude(m => m.Alumno)
                        .ThenInclude(a => a.Usuario)
                .Include(n => n.Aula)
                .Include(n => n.Materia)
                .AsQueryable();

            if (nota.Matricula != null && !string.IsNullOrWhiteSpace(nota.Matricula.Alumno.Usuario.NombreUsuario))
                query = query.Where(s => s.Matricula.Alumno.Usuario.NombreUsuario.Contains(nota.Matricula.Alumno.Usuario.NombreUsuario));

            if (nota.Materia != null && !string.IsNullOrWhiteSpace(nota.Materia.Nombre))
                query = query.Where(s => s.Materia.Nombre.Contains(nota.Materia.Nombre));

            if (nota.Aula != null && !string.IsNullOrWhiteSpace(nota.Aula.Nombre))
                query = query.Where(s => s.Aula.Nombre.Contains(nota.Aula.Nombre));


            if (topRegistro > 0)
                query = query.Take(topRegistro);

            return View(await query.ToListAsync());
        }


        // GET: Notas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .Include(n => n.Aula)
                .Include(n => n.Materia)
                .Include(n => n.Matricula)
                    .ThenInclude(m => m.Alumno)
                        .ThenInclude(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }


        // GET: Notas/Create
        // GET: Notas/Create
        public IActionResult Create()
        {
            // Obtener alumnos con el nombre del usuario
            ViewData["IdMatricula"] = new SelectList(
                _context.Matriculas
                    .Include(m => m.Alumno)
                    .ThenInclude(a => a.Usuario),
                "IdMatricula",
                "Alumno.Usuario.NombreUsuario"
            );

            // Obtener aulas y materias
            ViewData["IdAula"] = new SelectList(_context.Aulas, "Id", "Nombre");
            ViewData["IdMateria"] = new SelectList(_context.Materias, "Id", "Nombre");

            return View();
        }

        // POST: Notas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMatricula,IdAula,IdMateria,Trimestre1,Trimestre2,Trimestre3,Promedio,Estado")] Nota nota)
        {
            // Validar si los trimestres tienen valor
            if (nota.Trimestre1 == 0 || nota.Trimestre2 == 0 || nota.Trimestre3 == 0)
            {
                ModelState.AddModelError("", "Todos los trimestres deben tener un valor mayor que 0.");
            }

            // Validar que el modelo sea válido
            if (ModelState.IsValid)
            {
                try
                {
                    // Asegurarse de que los trimestres sean válidos antes de realizar el cálculo
                    decimal trimestre1 = nota.Trimestre1;
                    decimal trimestre2 = nota.Trimestre2;
                    decimal trimestre3 = nota.Trimestre3;

                    // Cálculo del promedio de los trimestres
                    var promedio = (trimestre1 + trimestre2 + trimestre3) / 3;
                    nota.Promedio = promedio;

                    // Calcular el estado basado en el promedio
                    nota.Estado = (nota.Promedio >= 6) ? "Aprobado" : "Reprobado";

                    // Guardar la nota en la base de datos
                    _context.Add(nota);
                    await _context.SaveChangesAsync();

                    // Redirigir a la acción Index después de guardar la nueva nota
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Si ocurre un error durante el guardado, mostrar el error
                    ModelState.AddModelError("", "Hubo un error al guardar los datos: " + ex.Message);
                }
            }

            // Si el modelo no es válido o hubo error, recargar las listas para los campos del formulario
            ViewData["IdMatricula"] = new SelectList(_context.Matriculas
                .Include(m => m.Alumno)
                .ThenInclude(a => a.Usuario)
                .Select(m => new {
                    m.IdMatricula,
                    NombreAlumno = m.Alumno.Usuario.NombreUsuario
                }),
                "IdMatricula", "NombreAlumno", nota.IdMatricula);

            ViewData["IdAula"] = new SelectList(_context.Aulas, "Id", "Nombre", nota.IdAula);
            ViewData["IdMateria"] = new SelectList(_context.Materias, "Id", "Nombre", nota.IdMateria);

            return View(nota);
        }

        // GET: Notas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas.FindAsync(id);
            if (nota == null)
            {
                return NotFound();
            }

            ViewData["IdAula"] = new SelectList(_context.Aulas, "Id", "Nombre", nota.IdAula);
            ViewData["IdMateria"] = new SelectList(_context.Materias, "Id", "Nombre", nota.IdMateria);

            ViewData["IdMatricula"] = new SelectList(
                _context.Matriculas
                    .Include(m => m.Alumno)
                    .ThenInclude(a => a.Usuario)
                    .Select(m => new {
                        m.IdMatricula,
                        NombreAlumno = m.Alumno.Usuario.NombreUsuario
                    }).ToList(),
                "IdMatricula",
                "NombreAlumno",
                nota.IdMatricula
            );

            return View(nota);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdMatricula,IdAula,IdMateria,Trimestre1,Trimestre2,Trimestre3,Promedio,Estado")] Nota nota)
        {
            if (id != nota.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotaExists(nota.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdAula"] = new SelectList(_context.Aulas, "Id", "Nombre", nota.IdAula);
            ViewData["IdMateria"] = new SelectList(_context.Materias, "Id", "Nombre", nota.IdMateria);

            ViewData["IdMatricula"] = new SelectList(
                _context.Matriculas
                    .Include(m => m.Alumno)
                    .ThenInclude(a => a.Usuario)
                    .Select(m => new {
                        m.IdMatricula,
                        NombreAlumno = m.Alumno.Usuario.NombreUsuario
                    }).ToList(),
                "IdMatricula",
                "NombreAlumno",
                nota.IdMatricula
            );

            return View(nota);
        }

        private bool NotaExists(int id)
        {
            throw new NotImplementedException();
        }


        // GET: Notas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .Include(n => n.Aula)
                .Include(n => n.Materia)
                .Include(n => n.Matricula)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // POST: Notas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var nota = await _context.Notas.FindAsync(id);
            if (nota == null)
            {
                return NotFound();
            }

            _context.Notas.Remove(nota);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

HELMA20250404.AppMVCCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HELMA20250404.AppMVCCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/site-custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .navbar {
            z-index: 1000;
            height: 70px;
            padding-top: 0;
            padding-bottom: 0;
            background-color: #fbfcfc;
        }

        .layout-wrapper {
            display: flex;
            flex: 1;
            margin-top: 56px;
        }

        .sidebar {
            width: 200px;
            background: oklch(95.6% 0.045 203.388);
            color: white;
            height: calc(100vh - 56px);
            position: sticky;
            top: 56px;
            padding-top: 3rem;
            overflow-y: auto;
            flex-shrink: 0;
        }

        .sidebar a {
            color: black;
            padding: 12px 20px;
            display: block;
            text-decoration: none;
            font-size: 1rem;
            transition: background-color 0.3s ease, transform 0.2s ease;
        }

        .sidebar a:hover {
            background-color: oklch(86.9% 0.022 252.894);
            transform: translateX(8px);
        }

        .main-content {
            flex-grow: 1;
            padding: 30px;
            background-color: #fff;
        }

        footer {
            background-color: #fff;
            padding: 10px 0;
        }

        .top-links a {
            margin-left: 15px;
            text-decoration: none;
            color: #007bff;
            font-weight: 500;
            transition: color 0.3s ease;
        }

        .top-links a:hover {
            text-decoration: underline;
            color: #0056b3;
        }

        .navbar-brand {
            font-size: 1.25rem;
            font-weight: bold;
            color: #343a40;
        }

        .navbar-brand span {
            font-size: 1.5rem;
            color: #007bff;
            font-weight: 600;
            margin-left: 10px;
        }

        .logo-img {
            height: 60px;
            margin-right: 0px;
            margin-top: 0px;
        }

        .sctexto {
            color: #003366;
            font-weight: 300;
            margin-left: 0px;
            margin-right: 0px;
		
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light border-bottom shadow-sm fixed-top">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="\images\logo.png" alt="Logo" class="logo-img img-fluid">
                        <span class="sctexto">Sistema de Calificaciones</span>
                    </a>

                    <div class="top-links">
                        <a asp-area="" asp-controller="Home" asp-action="Index" style="text-decoration: none;"><i class="bi bi-house"></i> Home</a>
                        <a asp-area="" asp-controller="Home" asp-action="Privacy" style="text-decoration: none;"><i class="bi bi-shield-lock"></i> Privacy</a>
                    </div>
                </div>
                <div class="d-flex align-items-center">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="ChancePassword">Cambiar password</a>
                        <a class="nav-link text-dark d-flex align-items-center" asp-area="" asp-controller="Usuarios" asp-action="CerrarSession">
                            <i class="bi bi-box-arrow-in-right me-2"></i> Cerrar sesión
                        </a>
                        <span>@User.Identity.Name</span>
                    }
                    else
                    {
                        <a class="btn btn-primary rounded-pill px-4 d-flex align-items-center" asp-area="" asp-controller="Usuarios" asp-action="Login">
                            <i class="bi bi-person-circle me-2"></i> Iniciar sesión
                        </a>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="layout-wrapper">
        <div class="sidebar">
            @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("ADMINISTRADOR"))
                {
                    <a asp-controller="Usuarios" asp-action="Index"><i class="bi bi-people"></i> Usuarios</a>
                    <a asp-controller="Alumnos" asp-action="Index"><i class="bi bi-mortarboard"></i> Alumnos</a>
                    <a asp-controller="Materias" asp-action="Index"><i class="bi bi-book"></i> Materias</a>
                    <a asp-controller="Aulas" asp-action="Index"><i class="bi bi-journal-text"></i> Aulas</a>
                    <a asp-controller="Profesores" asp-action="Index"><i class="bi bi-journal-text"></i> Profesores</a>
                }
                @if (User.IsInRole("PROFESOR"))
                {
                    <a asp-controller="Matriculas" asp-action="Index"><i class="bi bi-journal-text"></i> Matriculas</a>
                    <a asp-controller="Notas" asp-action="Index"><i class="bi bi-journal-text"></i> Notas</a>
                    <a asp-controller="Alumnos" asp-action="Index"><i class="bi bi-mortarboard"></i> Alumnos</a>
                }
                @if (User.IsInRole("ALUMNO"))
                {
                    <a asp-controller="Notas" asp-action="Index"><i class="bi bi-journal-text"></i> Notas</a>
                }
            }
        </div>

        <div class="main-content">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
            <footer class="border-top footer text-muted text-center mt-4">
                <div class="container">
                    &copy; 2025 - HELMA20250404.AppMVCCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('select').select2();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>